baseURL = 'https://robexley.github.io/nidderdale-project/'
languageCode = 'en-us'
title = 'Nidderdale Project'
copyright = "robexley"
theme = "ananke"

[params]
background_color_class = "bg-dark-green"